### ISSUE TITLE
.getKey() hangs if I2C expander module is reset

### ISSUE THREAD

**Issue by sebgiles** [joeyoung/arduino_keypads#3]
I tried to implement my own waitForKey() to add a timeout, the code is simply:
(This doesn't actually return the key being pressed but is just a way to recreate the problem on Arduino Uno)

```
//returns true if TIMEOUT occurs
bool waitForKey(unsigned long max_time) {
  unsigned long startTime = millis();
  while (!kpd.getKey()) {
    if (millis() - startTime > max_time) {
      return true;
    }
  }
  return false;
}
```

If the I2c expander module is turned off and on whilst the waitForKey() function is running the getKey() function will never return. This off/on may even be caused by very brief power supply glitches.

In my application I have worked around the problem by using a watchdog.

I have not looked closely at any of this source but I think there are 3 ways to improve the situation:

1. getKey returns some identifiable value in the case of error (favourite solution but may interfere with user keymaps)
2. getKey returns 0 as if no key was read (least favourite solution). 
3. getKey internally runs kpd.begin() to solve the problem (might as well if it's just hanging)

**Comment by joeyoung** [comment]
In the absence of requested clarification, the developers have decided this is a non-issue. The I2C port expander should not malfunction during normal operation and it's not the responsibility of the keypad library to handle a hardware failure. There does not seem to be any normal operation that could benefit from a .getKey( ) timeout, and it can be accomplished in other ways. No changes are contemplated.
