### ISSUE TITLE
Two question not issues!

### ISSUE THREAD

**Issue by beicnet** [joeyoung/arduino_keypads#4]
Hi there,

I have two question:
1. Is the library working on ESP platform (WeMos D1 mini)?
2. How can I define Keypads like this ones (more or less buttons):
![image](https://user-images.githubusercontent.com/22061547/61733701-a65c5980-ad80-11e9-81f0-45fb9c59d8e7.png)
![image](https://user-images.githubusercontent.com/22061547/61733801-e28fba00-ad80-11e9-95e2-fa178e37c2cd.png)
![image](https://user-images.githubusercontent.com/22061547/61733860-fdfac500-ad80-11e9-87fa-90662cfe6b72.png)
![image](https://user-images.githubusercontent.com/22061547/61733889-136fef00-ad81-11e9-88a6-67dff7a58504.png)

Thank you! ;-)

**Comment by joeyoung** [comment]
1. The library is an arduino library, uses arduino timers for key debouncing, and depends on the arduino loop( ) structure. I have no experience with the ESP platforms, but as far as I know, they are not directly supported by the arduino IDE except possibly as a peripheral on certain arduino boards. With the ESP as a peripheral, the arduino could handle the keypad.

2. The library can handle up to 8 inputs arranged in rows and columns in any way that totals 8. So, eg a 4 key keypad could use a matrix of 4 X 1 (5 inputs) if each key was separate, or a matrix of 2 X 2  (4 inputs) if the keypad was connected that way. To use more than 16 keys (4 X 4 ) you can create more than one keypad object. Multiple keypad objects is convenient when using I2C I/O.

...Joe
