### ISSUE TITLE
Specified folder/zip file does not contain a valid library

### ISSUE THREAD

**Issue by daveHyder** [joeyoung/arduino_keypads#6]
hello.
I have problem and i still dont know the solution. I can't add this library and always said "Specified folder/zip file does not contain a valid library"
what should i do? i've followed every instructions to install libraary. I've added .zip library, I've tried manual installation, and even I've tried similiar way like Raynman77 (whom is have same issue) from the another room discussion, but it still didnt work for me, what should i do?

**Comment by joeyoung** [comment]
The .zip file will contain several libraries, not just a single valid library. Normally, one would want only one of the libraries that handles the I2C port expander to be used. For instance, the simplest port expander is the PCF8574, for which the Keypad_I2C would be used. The simplest way to handle getting that library available from this repository would be to d/l the .zip file, unzip in a convenient location, then move only the Keypad_I2C folder into your arduino libraries. You could also unzip the download to the arduino libraries folder and get all of the libraries at once.
